config/routes.rb
# config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'patients#index'

  devise_for :users

  resources :patients do
    resources :evaluations
    resources :therapeutic_plans do
      resources :therapeutic_sessions
    end
    resources :audits
    resources :family_meetings
    resources :school_feedbacks
  end

  resources :companies
  resources :clinics do
    resources :professionals
  end
  resources :schools
  resources :supervisors

  mount Sidekiq::Web => '/sidekiq'
  
end

app/models/audit.rb
class Audit < ApplicationRecord
  belongs_to :patient
  belongs_to :supervisor

  validates :data_auditoria, :detalhes, presence: true
end

app/models/autismia.rb
class Autismia < ApplicationRecord
  has_many :supervisors

  validates :nome, presence: true
end

app/models/clinic.rb
class Clinic < ApplicationRecord
  has_many :patient_clinics
  has_many :patients, through: :patient_clinics

  has_many :professionals
  has_many :therapeutic_sessions

  validates :nome_clinica, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :patients

  validates :nome_plano, presence: true
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :patient

  validates :data_avaliacao, :tipo_avaliacao, :resultado_avaliacao, presence: true
end

app/models/family_meeting.rb
class FamilyMeeting < ApplicationRecord
  belongs_to :patient
  belongs_to :supervisor

  validates :data_reuniao, :descricao, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :school, optional: true
  belongs_to :company, optional: true # Plano de saúde

  has_many :evaluations, dependent: :destroy
  has_many :therapeutic_plans, dependent: :destroy
  has_many :audits, dependent: :destroy
  has_many :family_meetings, dependent: :destroy
  has_many :school_feedbacks, dependent: :destroy

  has_many :patient_clinics
  has_many :clinics, through: :patient_clinics

  validates :nome, :data_nascimento, :responsavel_principal, presence: true
end

app/models/patient_clinic.rb
class PatientClinic < ApplicationRecord
  belongs_to :patient
  belongs_to :clinic

  validates :data_inicio, presence: true
end

app/models/professional.rb
class Professional < ApplicationRecord
  belongs_to :clinic

  has_many :therapeutic_sessions

  validates :nome, :funcao, presence: true
end

app/models/report.rb
class Report < ApplicationRecord
  acts_as_tenant(:company)
  belongs_to :patient
  belongs_to :company

  has_one :report_resume, dependent: :destroy
  
  validates :content, presence: true
end

app/models/report_resume.rb
class ReportResume < ApplicationRecord
  belongs_to :report

  validates :content, presence: true
end

app/models/school.rb
class School < ApplicationRecord
  has_many :patients

  validates :nome_escola, presence: true
end

app/models/school_feedback.rb
class SchoolFeedback < ApplicationRecord
  belongs_to :patient
  belongs_to :supervisor

  validates :data_feedback, :observacoes, presence: true
end

app/models/summary.rb
class Summary < ApplicationRecord
  belongs_to :therapeutic_session

  validates :content, presence: true
end

app/models/supervisor.rb
class Supervisor < ApplicationRecord
  belongs_to :autismia

  has_many :audits
  has_many :family_meetings
  has_many :school_feedbacks

  validates :nome, presence: true
end

app/models/therapeutic_plan.rb
class TherapeuticPlan < ApplicationRecord
  belongs_to :patient

  has_many :therapeutic_sessions

  validates :data_inicio, :objetivos, :status, presence: true
end

app/models/therapeutic_session.rb
class TherapeuticSession < ApplicationRecord
  belongs_to :therapeutic_plan
  belongs_to :professional
  belongs_to :clinic

  has_one :summary, dependent: :destroy
  
  validates :data_sessao, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Devise modules para autenticação
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associações
  belongs_to :company
  has_many :patients, dependent: :destroy

  # Validações
  validates :company, presence: true
  validates :name, presence: true
  
  enum role: { admin: 0, company_user: 1, professional: 2, supervisor: 3 }

  def admin?
    role == 'admin'
  end
  
end

app/controllers/audits_controller.rb
class AuditsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient
  before_action :set_audit, only: %i[show edit update destroy]

  def index
    @audits = @patient.audits
  end

  def show
    # @audit já está definido
  end

  def new
    @audit = @patient.audits.build
  end

  def create
    @audit = @patient.audits.build(audit_params)
    if @audit.save
      redirect_to [@patient, @audit], notice: 'Auditoria criada com sucesso.'
    else
      render :new
    end
  end

  def edit
    # @audit já está definido
  end

  def update
    if @audit.update(audit_params)
      redirect_to [@patient, @audit], notice: 'Auditoria atualizada com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @audit.destroy
    redirect_to patient_audits_path(@patient), notice: 'Auditoria excluída com sucesso.'
  end

  private

  def set_patient
    @patient = Patient.find(params[:patient_id])
  end

  def set_audit
    @audit = @patient.audits.find(params[:id])
  end

  def audit_params
    params.require(:audit).permit(
      :supervisor_id,
      :data_auditoria,
      :detalhes,
      :conclusao,
      :proxima_auditoria
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/analysis/new.html.erb
<%# app/views/analysis/new.html.erb %>
<h1>Insira o texto para gerar um resumo</h1>
<%= form_with url: '/analysis/create_summary', method: :post, local: true do |form| %>
  <div>
    <%= form.label :content, "Texto para resumo" %><br>
    <%= form.text_area :content, rows: 10, cols: 50 %>
  </div>
  <br>
  <%= form.submit "Gerar Resumo" %>
<% end %>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->

<!DOCTYPE html>
<html>
<head>
  <title>PatientAnalysis</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>

</head>

<body>
  <nav>
    <% if user_signed_in? %>
    <%= link_to 'Home', root_path %> |
    <%= link_to 'Pacientes', patients_path %> |
    <%= link_to 'Clínicas', clinics_path %> |
    <%= link_to 'Profissionais', clinics_path %> |
    <%= link_to 'Escolas', schools_path %> |
    <%= link_to 'Planos de Saúde', companies_path %> |
    <%= form_with url: destroy_user_session_path, method: :delete do %>
      <%= submit_tag 'Sair' %>
      <% end %>
    <% else %>
      <%= link_to 'Entrar', new_user_session_path %>
    <% end %>
  </nav>

  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <%= yield %>
</body>
</html>